"""func1

Revision ID: 8b296bf68af0
Revises: 002e9d1c9d8c
Create Date: 2023-09-28 23:25:50.843953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b296bf68af0'
down_revision: Union[str, None] = '002e9d1c9d8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['id'])
    op.create_unique_constraint(None, 'functions', ['id'])
    op.create_unique_constraint(None, 'psychotypes4d', ['id'])
    op.add_column('questions', sa.Column('to_func', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'questions', ['id'])
    op.drop_constraint('questions_to_psytype_fkey', 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'functions', ['to_func'], ['id'])
    op.drop_column('questions', 'to_psytype')
    op.create_unique_constraint(None, 'testpassings', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'testpassings', type_='unique')
    op.add_column('questions', sa.Column('to_psytype', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key('questions_to_psytype_fkey', 'questions', 'functions', ['to_psytype'], ['id'])
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'to_func')
    op.drop_constraint(None, 'psychotypes4d', type_='unique')
    op.drop_constraint(None, 'functions', type_='unique')
    op.drop_constraint(None, 'answers', type_='unique')
    # ### end Alembic commands ###
